// scripts/build-status.mjs — a LIVE build-progress board for a game, pinned at the TOP.
// Reads the game's GAME_META.stages against the full pipeline (single source of truth:
// tools/lib/pipeline.mjs) and renders a progress bar + the stage tree (✓/○) + the NEXT pointer.
// It PINS this at the very top of <game>/README.md (between markers) so it's the first thing on the
// repo's front page, and prints it. Run it after every stage (it's idempotent):
//
//   node scripts/build-status.mjs <game-dir>
//
// Pair it with `scripts/make-game-issues.mjs` (which keeps the pinned tracker ISSUE in sync) — the
// README board is the at-a-glance view, the tracker issue is the actionable one.
import fs from 'node:fs';
import path from 'node:path';
import { PIPELINE, treeMarkdown } from '../tools/lib/pipeline.mjs';

const dir = process.argv[2];
if (!dir) { console.error('usage: node scripts/build-status.mjs <game-dir>'); process.exit(2); }
const meta = JSON.parse(fs.readFileSync(path.join(dir, 'GAME_META.json'), 'utf8'));
const stages = meta.stages || {};
const doneMap = {};
PIPELINE.forEach((s) => { if (stages[s.key] === 'done') doneMap[s.key] = 'done'; });
const total = PIPELINE.length;
const done = PIPELINE.filter((s) => doneMap[s.key]).length;
const next = PIPELINE.find((s) => !doneMap[s.key]);
const pct = Math.round((done / total) * 100);
const FILL = 24, fl = Math.round((done / total) * FILL);
const bar = '▰'.repeat(fl) + '▱'.repeat(FILL - fl);

const board = [
  '<!-- BUILD:START (generated by scripts/build-status.mjs — do not edit by hand) -->',
  `## 🚧 ${meta.name || 'Game'} — build progress · ${done}/${total} stages (${pct}%)`,
  '',
  '```',
  `${bar}  ${done}/${total}`,
  next ? `👉 NEXT: ${PIPELINE.indexOf(next) + 1}. ${next.title}` : '🎉 ALL STAGES DONE — shipped.',
  '```',
  '',
  treeMarkdown(doneMap),
  '<!-- BUILD:END -->',
].join('\n');

const readmePath = path.join(dir, 'README.md');
let readme = fs.existsSync(readmePath) ? fs.readFileSync(readmePath, 'utf8') : `# ${meta.name || 'Game'}\n`;
const re = /<!-- BUILD:START[\s\S]*?<!-- BUILD:END -->\n?/;
if (re.test(readme)) readme = readme.replace(re, board + '\n');
else {                                  // insert right after the first H1 (keep the title on top)
  const m = readme.match(/^(#[^\n]*\n)/);
  readme = m ? readme.slice(0, m[0].length) + '\n' + board + '\n\n' + readme.slice(m[0].length) : board + '\n\n' + readme;
}
fs.writeFileSync(readmePath, readme);
console.log(board.replace(/<!--[^>]*-->\n?/g, ''));
console.log(`\n→ pinned at the top of ${path.relative(process.cwd(), readmePath)}`);
