// tools/art-tiles.mjs — ENGINE themed-tile generator (#22). One claymation GROUND texture per
// material (a side-view clay block: a clay top surface + body) → src/assets/tiles/<key>.<ext>.
// The game preloads them as `tile_<mat>`; Studio.Level.build prefers `tile_<mat>` over the baked
// materialTile, and Textures.kit skips baking when a generated tile is loaded. Matches the
// claymation backdrops so the ground stops reading as a flat gradient.
//
//   node tools/art-tiles.mjs <gameDir> [--force]
//
// Needs a Gemini SA (GEMINI_SA_JSON). Skips cleanly if absent. Cached via gencache. Merges into
// the sprites manifest (manifest.json + src/game/sprites.js) so one include covers all art.
import fs from 'node:fs';
import path from 'node:path';
import { generateImage, geminiConfigured } from '../scripts/gemini.js';
import { cached } from './lib/gencache.mjs';

const gameDir = process.argv[2];
if (!gameDir) { console.error('usage: node tools/art-tiles.mjs <gameDir> [--force]'); process.exit(2); }
if (!geminiConfigured()) { console.error('No Gemini SA — skipping tile art (the game keeps the baked materialTile).'); process.exit(0); }

const meta = JSON.parse(fs.readFileSync(path.join(gameDir, 'GAME_META.json'), 'utf8'));
const tiles = (meta.art && meta.art.tiles) || [];
if (!tiles.length) { console.log('no meta.art.tiles declared — nothing to do.'); process.exit(0); }
const style = (meta.art && meta.art.style) || 'bold cartoon';
const cacheDir = path.join(gameDir, '.cache');
const outDir = path.join(gameDir, 'src/assets/tiles');
fs.mkdirSync(outDir, { recursive: true });

const tileMap = {};
console.log(`\ntile art · ${tiles.length} materials`);
for (const t of tiles) {
  try {
    const prompt = `Side-view cross-section of ${t.desc}, ${style}. A clay top SURFACE with a soft rounded lip along the top edge and a solid clay body filling the rest, handmade fingerprint texture, vivid saturated color, soft studio light. The texture FILLS the entire frame edge to edge (no border, no background, no scene, no text).`;
    const c = await cached('tile', { key: t.key, desc: t.desc, style }, '.img',
      async () => { const { mimeType, base64 } = await generateImage(prompt, { aspectRatio: '16:9' }); return Buffer.from(JSON.stringify({ mimeType, base64 })); },
      { dir: cacheDir });
    const { mimeType, base64 } = JSON.parse(fs.readFileSync(c.path, 'utf8'));
    const ext = mimeType.includes('png') ? 'png' : 'jpg';
    const file = t.key + '.' + ext;
    fs.writeFileSync(path.join(outDir, file), Buffer.from(base64, 'base64'));
    tileMap[t.key] = 'tiles/' + file;
    process.stdout.write(`  ${t.key}${c.hit ? '·' : '✱'}`);
  } catch (e) { console.log(`\n  ✗ ${t.key}: ${e.message}`); }
}
console.log('');

// merge into the sprites manifest + sprites.js (so one <script> include covers hero+enemies+tiles)
const sprDir = path.join(gameDir, 'src/assets/sprites');
fs.mkdirSync(sprDir, { recursive: true });
const mPath = path.join(sprDir, 'manifest.json');
const full = fs.existsSync(mPath) ? JSON.parse(fs.readFileSync(mPath, 'utf8')) : {};
full.tiles = tileMap;
fs.writeFileSync(mPath, JSON.stringify(full, null, 2));
fs.writeFileSync(path.join(gameDir, 'src/game/sprites.js'), '/* generated by tools/art-*.mjs — real character + tile atlas (Studio loads it, falls back to procedural). */\nwindow.SPRITES = ' + JSON.stringify(full, null, 2) + ';\n');
console.log(`\n✅ ${Object.keys(tileMap).length} tiles → ${outDir} + merged into sprites.js`);
