// tools/art-props.mjs — ENGINE world-prop generator (#23). One green-screen, chroma-keyed
// sprite per prop (collectible / bounce pad / goal / decoration / hazard marker) from
// meta.art.props → src/assets/props/<key>.png. The game preloads them as `prop_<key>` and
// applies them (e.g. setTexture on coins/goal/pads). Merged into the sprites manifest.
//
//   node tools/art-props.mjs <gameDir> [--force]   (needs GEMINI_SA_JSON; skips cleanly if absent)
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { generateImage, geminiConfigured } from '../scripts/gemini.js';
import { cached } from './lib/gencache.mjs';

const gameDir = process.argv[2];
if (!gameDir) { console.error('usage: node tools/art-props.mjs <gameDir> [--force]'); process.exit(2); }
if (!geminiConfigured()) { console.error('No Gemini SA — skipping prop art.'); process.exit(0); }
const meta = JSON.parse(fs.readFileSync(path.join(gameDir, 'GAME_META.json'), 'utf8'));
const props = (meta.art && meta.art.props) || [];
if (!props.length) { console.log('no meta.art.props declared — nothing to do.'); process.exit(0); }
const style = (meta.art && meta.art.style) || 'bold cartoon';
const cacheDir = path.join(gameDir, '.cache');
const outDir = path.join(gameDir, 'src/assets/props');
fs.mkdirSync(outDir, { recursive: true });
const GREEN = 'FLAT SOLID GREEN (#00d800) background everywhere — nothing else: no ground, no shadow, no text.';

async function genPNG(key, prompt) {
  const c = await cached('prop', { key, prompt }, '.png', async () => { const { base64 } = await generateImage(prompt, { aspectRatio: '1:1' }); return Buffer.from(base64, 'base64'); }, { dir: cacheDir });
  return c;
}
console.log(`\nprop art · ${props.length} props`);
const raw = {};
for (const p of props) {
  const c = await genPNG(p.key, `${p.desc}, ${style}. ONE object, centered, full object in frame, no other objects. ${GREEN}`);
  raw[p.key] = c.path; process.stdout.write(`  ${p.key}${c.hit ? '·' : '✱'}`);
}
console.log('');

// chroma-key + trim each prop → its own PNG
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage();
const propMap = {};
for (const p of props) {
  const url = 'data:image/png;base64,' + fs.readFileSync(raw[p.key]).toString('base64');
  const out = await page.evaluate(async (u) => {
    function load(x) { return new Promise((res, rej) => { const im = new Image(); im.onload = () => res(im); im.onerror = rej; im.src = x; }); }
    const im = await load(u); const c = document.createElement('canvas'); c.width = im.naturalWidth; c.height = im.naturalHeight;
    const x = c.getContext('2d'); x.drawImage(im, 0, 0); const id = x.getImageData(0, 0, c.width, c.height); const d = id.data;
    for (let i = 0; i < d.length; i += 4) { const r = d[i], g = d[i + 1], b = d[i + 2];
      if (g > 90 && g > r * 1.25 && g > b * 1.25) d[i + 3] = 0;
      else if (g > r && g > b && g - Math.max(r, b) > 28) { d[i] = r * .7; d[i + 2] = b * .7; d[i + 3] = Math.max(0, d[i + 3] - 80); } }
    x.putImageData(id, 0, 0);
    let x0 = c.width, y0 = c.height, x1 = 0, y1 = 0;
    for (let yy = 0; yy < c.height; yy++) for (let xx = 0; xx < c.width; xx++) { if (d[(yy * c.width + xx) * 4 + 3] > 24) { if (xx < x0) x0 = xx; if (xx > x1) x1 = xx; if (yy < y0) y0 = yy; if (yy > y1) y1 = yy; } }
    if (x1 < x0) { x0 = 0; y0 = 0; x1 = c.width - 1; y1 = c.height - 1; }
    const w = x1 - x0 + 1, h = y1 - y0 + 1; const tc = document.createElement('canvas'); tc.width = w; tc.height = h;
    tc.getContext('2d').drawImage(c, x0, y0, w, h, 0, 0, w, h); return tc.toDataURL('image/png');
  }, url);
  fs.writeFileSync(path.join(outDir, p.key + '.png'), Buffer.from(out.split(',')[1], 'base64'));
  propMap[p.key] = 'props/' + p.key + '.png';
  console.log(`  ${p.key} → ${p.key}.png`);
}
await browser.close();

const sprDir = path.join(gameDir, 'src/assets/sprites'); fs.mkdirSync(sprDir, { recursive: true });
const mPath = path.join(sprDir, 'manifest.json');
const full = fs.existsSync(mPath) ? JSON.parse(fs.readFileSync(mPath, 'utf8')) : {};
full.props = propMap;
fs.writeFileSync(mPath, JSON.stringify(full, null, 2));
fs.writeFileSync(path.join(gameDir, 'src/game/sprites.js'), '/* generated by tools/art-*.mjs — character + tile + prop atlas. */\nwindow.SPRITES = ' + JSON.stringify(full, null, 2) + ';\n');
console.log(`\n✅ ${Object.keys(propMap).length} props → ${outDir} + merged into sprites.js`);
