// tools/design-pass.mjs — #41 the DESIGN stage tool. Runs the feel model (#35) + design-intent
// schema (#36) over a game's real levels and reports per-level FUN (engagement/dynamics/arc/flow),
// the interest-curve sparkline, weakest/strongest, dead-air flags, and whether each level matches
// its intent (signature present, climax late). Writes DESIGN.md + design.json that the build / the
// in-game /design page read. Run BEFORE art/music in the pipeline.
//
//   node tools/design-pass.mjs <gameDir> [--write]
import fs from 'node:fs';
import path from 'node:path';
import { funReport } from './lib/feelmodel.mjs';
import { campaignDesign } from './lib/design.mjs';

const gameDir = process.argv[2];
if (!gameDir) { console.error('usage: node tools/design-pass.mjs <gameDir> [--write]'); process.exit(2); }
const write = process.argv.includes('--write');

const src = fs.readFileSync(path.join(gameDir, 'src', 'game', 'levels.js'), 'utf8');
const g = {}; new Function('window', src)(g);
const LEVELS = g.LEVELS || [];
if (!LEVELS.length) { console.error('no window.LEVELS'); process.exit(1); }

const SPARK = '▁▂▃▄▅▆▇█';
const spark = (curve) => curve.map((v) => SPARK[Math.max(0, Math.min(7, Math.round((v / 10) * 7)))]).join('');

const rep = funReport(LEVELS);
const design = campaignDesign(LEVELS);

console.log(`\n🎨 design-pass · ${gameDir}\n`);
rep.rows.forEach((r, i) => {
  const c = r.components, chk = design.checks[i];
  console.log(`  L${i + 1} ${(r.name || '').padEnd(20)} FUN ${String(r.fun).padStart(4)}  ${spark(r.curve)}`);
  console.log(`      eng ${c.engagement} · dyn ${c.dynamics} · arc ${c.arc} · flow ${c.flow}   peak@${r.peakPos}${r.deadAir.length ? `   dead-air: ${r.deadAir.length} win` : ''}${chk.ok ? '   ✓ intent' : '   ✗ ' + chk.issues.join('; ')}`);
});
console.log(`\n  campaign mean FUN ${rep.mean} · weakest ${rep.weakest.name} (${rep.weakest.fun}) · strongest ${rep.strongest.name} (${rep.strongest.fun})`);
console.log(`  intent: ${design.ok ? 'all levels match' : design.checks.filter((c) => !c.ok).length + ' level(s) off-intent'}\n`);

if (write) {
  const md = [`# Design — ${path.basename(gameDir)}`, '', `Generated by \`tools/design-pass.mjs\`. Mean FUN **${rep.mean}**.`, '',
    '| Level | FUN | curve | eng | dyn | arc | flow | intent |', '|---|---|---|---|---|---|---|---|',
    ...rep.rows.map((r, i) => `| ${r.name} | ${r.fun} | \`${spark(r.curve)}\` | ${r.components.engagement} | ${r.components.dynamics} | ${r.components.arc} | ${r.components.flow} | ${design.checks[i].ok ? '✓' : '✗ ' + design.checks[i].issues.join('; ')} |`),
  ].join('\n');
  fs.writeFileSync(path.join(gameDir, 'DESIGN.md'), md + '\n');
  fs.mkdirSync(path.join(gameDir, 'src'), { recursive: true });
  fs.writeFileSync(path.join(gameDir, 'src', 'design.json'), JSON.stringify({ meanFun: rep.mean, levels: design.intents, checks: design.checks }, null, 2));
  console.log(`  ✍️  wrote ${gameDir}/DESIGN.md + src/design.json (read by /design)\n`);
}
